### ISSUE TITLE
New custom post is not counting

### ISSUE THREAD

**Issue by kieusonlam** [a3rev/page-views-count#12]
I have a custom post type, it's work fine with old post from that cpt. But new posts is not counting any new view. Any idea?

My website: https://nguonhocbong.com/scholarships/

**Comment by alextuan** [comment]
Hi

Are you from Vietnam ? Can you explain bit about the issue you are getting, give me the page url that it does not count any view.

**Comment by kieusonlam** [comment]
@alextuan Yes, I'm from Vietnam.

Sorry for my bad explain, as you can see 3 newest posts in that page, doesn't count any new view ` No views yet` no matter how many time you view them. All another is working.

**Reproduce:**
1. Go to the URL above
2. Click any three of newest post
3. The counter is still 0

**Comment by alextuan** [comment]
@kieusonlam I have double check at my local but don't see that issue on new posts
I can help you if you can give me access to ftp, database and WP Dashboard 

Send that information directly to my email address mr.nguyencongtuan@gmail.com
