### ISSUE TITLE
Additional Security Improvements For Shortcode

### ISSUE THREAD

**Issue by PluginVulnerabilities** [a3rev/page-views-count#22]
While reviewing the changes made to address the vulnerability related to the plugin's pvc_stats shortcode in version 2.4.9, we noticed a couple of further security improvements that could be made to the parse_shortcode() function.

That code is using the extract() function on user input, in the form of shortcode parameter,s which is something that [PHP’s documentation](https://www.php.net/manual/en/function.extract.php) warns not to do:

>Do not use extract() on untrusted data, like user input (e.g. $_GET, $_FILES).

The postid parameter appears to be intended to only be an integer, so sanitizing or validating the value as an integer instead of using an escaping function to do the sanitization would be better. The function intval() could be used for sanitization or is_int() could be used for validation.

**Comment by a3rev** [comment]
Hello @PluginVulnerabilities 

Thank you for your report - we released a patch for it in[ version 2.4.12](https://github.com/a3rev/page-views-count/releases/tag/2.4.12) right after you the issue.

We received notification of the issue via email from the WordPress Plugin Review Team around the same time and did the patch.

But I never got to thank you on here and close this. 

Thank you
Steve
