### ISSUE TITLE
stopped showing today’s views

### ISSUE THREAD

**Issue by sspaeti** [a3rev/page-views-count#9]
see also https://wordpress.org/support/topic/stopped-showing-todays-views/

I noticed the same today. Using it for a long time, but since the last update, todays count is always 0.

Would be nice if you could fix that to not give a wrong impression to my users :-S
Best Simon

PS: see any blogs on http://www.sspaeti.com
--> I moved back now to version 2.0.0 to get the issue fixed as he mentioned:

tischtennis (@tischtennis):
I also use the plugin for a long time but now the same problem here at https://www.meteor-tt.de. No cache plugin is working. Downgrade to version 2.0.0 and all is good. But this is not the best solution. Please fix this.
Best Peter

**Comment by eric-enrico-roy** [comment]
Stefano has provided a way to fix this in the following post: https://wordpress.org/support/topic/stopped-showing-todays-views/

If that is so easy, can a developer add this to the code and get a new version ?

**Comment by a3rev** [comment]
@sspaeti , @eric-enrico-roy 

I am unsure if this is a bug report or a feature request? @sspaeti Simon seems to be reporting a bug while the post Eric has linked to is a way to turn OFF todays view count.

Can either of you confirm please what it is? or is it both ?

**Comment by sspaeti** [comment]
yes, i doesn't solve my issue when turning OFF today's views, still want to show them. Correct.

**Comment by a3rev** [comment]
@sspaeti, @eric-enrico-roy 

Have just put out version 2.0.4 - please update - it has the fix for this can't show Todays views.
